#!/usr/bin/env python

import sys, os

rel_path = os.path.join(os.getcwd() ,'eMart', 'manage.py')
with open(rel_path) as fi:
    file_content = fi.read()
    if 'eMart.settings.production' in file_content:
        print('##Changing to development environment in manage.py !')
        with open(rel_path, 'w') as fo:
            file_content = file_content.replace("eMart.settings.production", "eMart.settings.development")
            fo.write(file_content)
sys.exit(0)        